# on:
#   push:
#     branches:
#       - master
#       - develop

# jobs:
#   web-deploy-develop:
#     name: ðŸŽ‰ Deploy to zebrinha on push to develop
#     if: github.ref == 'refs/heads/develop'
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v3
    
#     - name: ðŸ“‚ Sync files to zebrinha
#       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#       with:
#         server: ${{ secrets.ftp_host }}
#         username: ${{ secrets.ftp_user }}
#         password: ${{ secrets.ftp_password }}
#         server-dir: /zebrinha.gjdesenvolvimento.com.br/

#   web-deploy-main:
#     name: ðŸŽ‰ Deploy to controlgj on push to main
#     if: github.ref == 'refs/heads/master'
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v3
    
#     - name: ðŸ“‚ Sync files to controlgj
#       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#       with:
#         server: ${{ secrets.ftp_host }}
#         username: ${{ secrets.ftp_user }}
#         password: ${{ secrets.ftp_password }}
#         server-dir: /controlgj.com.br/
